# Generated by Django 3.2.6 on 2021-08-13 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210813_0056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='historicalactor',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='historicalactor',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='historicalfilm',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='historicalfilm',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='historicalparticipation',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='historicalparticipation',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='participation',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='participation',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
