# Generated by Django 3.2.6 on 2021-08-31 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20210813_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='movies.actor'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='movies.film'),
        ),
    ]
